- name: Script Çalıştırma (PVC Üzerinde)
  hosts: localhost
  gather_facts: no
  vars:
    input1: "{{ input1 }}"
    input2: "{{ input2 }}"

  tasks:
    - name: Dizin oluştur (AWX kullanıcısı için)
      become: yes  # Root yetkisi al
      become_method: su  # Sudo yerine "su" kullan
      ansible.builtin.file:
        path: /var/lib/awx/projects
        state: directory
        mode: '0755'
        owner: awx
        group: 1000

    - name: Scripti indir
      become: yes  # Root yetkisi al
      become_method: su  # Sudo yerine "su" kullan
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/your-repo/awx_script.sh
        dest: /var/lib/awx/projects/awx_script.sh
        mode: '0755'

    - name: Scripti çalıştır
      become: yes  # Root yetkisi al
      become_method: su  # Sudo yerine "su" kullan
      ansible.builtin.shell:
        cmd: ./awx_script.sh "{{ input1 }}" "{{ input2 }}"
        chdir: /var/lib/awx/projects
      register: script_output

    - name: Çıktıyı göster
      ansible.builtin.debug:
        msg: "{{ script_output.stdout }}"
