---
- name: Run Script and Save Output
  hosts: localhost
  gather_facts: no
  vars:
    input1: "{{ input1 }}"
    input2: "{{ input2 }}"
    script_url: "https://raw.githubusercontent.com/testv1c/awxscript/main/awx_script.sh"
    output_file: "/var/lib/awx/projects/output.txt"
  tasks:
    - name: Ensure projects directory exists
      file:
        path: /var/lib/awx/projects
        state: directory
        mode: '0755'

    - name: Download the script from GitHub
      get_url:
        url: "{{ script_url }}"
        dest: "/var/lib/awx/projects/awx_script.sh"
        mode: '0755'

    - name: Run the script with inputs
      command: /bin/bash /var/lib/awx/projects/awx_script.sh "{{ input1 }}" "{{ input2 }}"
      register: script_output

    - name: Get hostname
      command: hostname
      register: hostname_output

    - name: Save outputs to a file
      copy:
        content: |
          Input1: {{ input1 }}
          Input2: {{ input2 }}
          Script Output: {{ script_output.stdout }}
          Hostname: {{ hostname_output.stdout }}
        dest: "{{ output_file }}"
