---
- name: AWX Playbook - Script İndirme ve Çalıştırma (`sh` içinde)
  hosts: localhost
  gather_facts: no
  vars:
    input1: "{{ input1 | default('Default Input 1') }}"
    input2: "{{ input2 | default('Default Input 2') }}"

  tasks:
    - name: GitHub'dan scripti çek (sh içinde çalıştır)
      shell: "/bin/sh -c 'curl -o /tmp/awx_script.sh https://raw.githubusercontent.com/testv1c/awxscript/main/awx_script.sh'"
      args:
        executable: /bin/sh

    - name: İndirilen scripti kontrol et
      stat:
        path: /tmp/awx_script.sh
      register: script_status

    - name: Script dosyasının var olup olmadığını göster
      debug:
        msg: "Script mevcut mu? {{ script_status.stat.exists }}"

    - name: "/tmp dizininde hangi dosyalar var? (Debug amaçlı)"
      shell: "ls -l /tmp"
      register: tmp_files

    - name: "/tmp içeriği"
      debug:
        msg: "{{ tmp_files.stdout_lines }}"

    - name: Dışarıdan scripti parametreler ile çalıştır
      shell: "/bin/bash /tmp/awx_script.sh '{{ input1 }}' '{{ input2 }}'"
      register: script_output
      when: script_status.stat.exists

    - name: Script çıktısını göster
      debug:
        msg: "{{ script_output.stdout }}"

    - name: Kalıcı volume içindeki dosyanın içeriğini oku
      command: cat /var/lib/awx/projects/script_output.txt
      register: file_output

    - name: Dosya içeriğini ekrana yazdır
      debug:
        msg: "{{ file_output.stdout }}"
