---
- name:script çalıştırma
  hosts: all
  become: yes
  vars:
    input1: "{{ input1 | default('varsayilan1') }}"
    input2: "{{ input2 | default('varsayilan2') }}"
  tasks:
    - name: Inputları parametre olarak göndererek script'i çalıştır
      command: "/usr/local/bin/print_hostname.sh {{ input1 }} {{ input2 }}"
      register: script_output

    - name: Script çıktısını görüntüle
      debug:
        var: script_output.stdout
