---
- name: Write input to a text file
  hosts: localhost
  gather_facts: false

  vars_prompt:
    - name: user_input
      prompt: "Please provide the text you want to write to the file"
      private: no

  tasks:
    - name: Create a directory for the output file
      file:
        path: /tmp/awx_output
        state: directory

    - name: Write user input to a text file
      copy:
        content: "{{ user_input }}"
        dest: /tmp/awx_output/output.txt

    - name: Display the output file path
      debug:
        msg: "Your input has been written to /tmp/awx_output/output.txt"
