---
- name: AWX Playbook - Script İndirme ve Çalıştırma (PVC Kullanımı)
  hosts: localhost
  gather_facts: no
  vars:
    input1: "{{ input1 | default('Default Input 1') }}"
    input2: "{{ input2 | default('Default Input 2') }}"

  tasks:
    - name: Projects dizinini oluştur (PVC için)
      file:
        path: /var/lib/awx/projects
        state: directory
        mode: '0777'

    - name: GitHub'dan scripti çek
      shell:
        cmd: curl -o awx_script.sh https://raw.githubusercontent.com/testv1c/awxscript/main/awx_script.sh
        chdir: /var/lib/awx/projects

    - name: Script dosyasının izinlerini değiştir
      file:
        path: /var/lib/awx/projects/awx_script.sh
        mode: '0755'

    # Diğer task'lar aynı kalabilir...
