---
- name: Script Çalıştırma (PVC Üzerinde)
  hosts: localhost
  gather_facts: no
  vars:
    input1: "{{ input1 | default('input1_varsayılan') }}"
    input2: "{{ input2 | default('input2_varsayılan') }}"

  tasks:
    # 1. Dizini oluştur (Zaten varsa etkisiz)
    - name: Dizin kontrolü
      ansible.builtin.file:
        path: /var/lib/awx/projects
        state: directory
        mode: '0755'

    # 2. Scripti indir
    - name: Scripti indir
      ansible.builtin.shell:
        cmd: curl -sS -O https://raw.githubusercontent.com/testv1c/awxscript/main/awx_script.sh
        chdir: /var/lib/awx/projects  # Komutun bu dizinde çalışması için

    # 3. Scripti çalıştır
    - name: Scripti çalıştır
      ansible.builtin.shell:
        cmd: ./awx_script.sh "{{ input1 }}" "{{ input2 }}"
        chdir: /var/lib/awx/projects
      register: script_output

    # 4. Çıktıyı göster
    - name: Sonuç
      ansible.builtin.debug:
        msg: "{{ script_output.stdout }}"
