---
- name: Script Çalıştırma (PVC Üzerinde)
  hosts: localhost
  gather_facts: no
  vars:
    input1: "{{ input1 | default('input1_varsayılan') }}"
    input2: "{{ input2 | default('input2_varsayılan') }}"

  tasks:
    # 1. Scripti GitHub'dan indir
    - name: Scripti indir
      ansible.builtin.shell:
        cmd: curl -sS -O https://raw.githubusercontent.com/testv1c/awxscript/main/awx_script.sh
        chdir: /var/lib/awx/projects  # PVC'ye yazmak için kritik
      register: download_result
      failed_when: download_result.rc != 0

    # 2. Scripti çalıştırılabilir yap
    - name: Script izinlerini ayarla
      ansible.builtin.file:
        path: /var/lib/awx/projects/awx_script.sh
        mode: '0755'
      when: download_result.rc == 0

    # 3. Scripti çalıştır (Output PVC'ye yazılacak)
    - name: Scripti çalıştır
      ansible.builtin.shell:
        cmd: ./awx_script.sh "{{ input1 }}" "{{ input2 }}"
        chdir: /var/lib/awx/projects  # Komutun PVC dizininde çalışması için
      register: script_output
      when: download_result.rc == 0

    # 4. Çıktıyı göster
    - name: Sonuç
      ansible.builtin.debug:
        msg: "{{ script_output.stdout }}"
