---
- name: Script Çalıştırma (PVC Üzerinde)
  hosts: localhost
  gather_facts: no
  vars:
    input1: "{{ input1 | default('input1_varsayılan') }}"
    input2: "{{ input2 | default('input2_varsayılan') }}"

  tasks:
    # 1. Scripti GitHub'dan PVC dizinine indir
    - name: Scripti indir
      ansible.builtin.shell:
        cmd: curl -sS -O https://raw.githubusercontent.com/testv1c/awxscript/main/awx_script.sh
        chdir: /var/lib/awx/projects  # Kritik! Komut bu dizinde çalışacak
      register: download_result
      failed_when: download_result.rc != 0  # Hata durumunda fail

    # 2. Script'e çalıştırma izni ver
    - name: Script izinlerini ayarla
      ansible.builtin.file:
        path: /var/lib/awx/projects/awx_script.sh  # Tam yol belirtilmeli
        mode: '0755'
      when: download_result.rc == 0  # Sadece indirme başarılıysa

    # 3. Scripti parametrelerle çalıştır
    - name: Scripti çalıştır
      ansible.builtin.shell:
        cmd: ./awx_script.sh "{{ input1 }}" "{{ input2 }}"
        chdir: /var/lib/awx/projects  # Komut bu dizinde çalışacak
      register: script_output
      when: download_result.rc == 0  # Sadece indirme başarılıysa

    # 4. Çıktıyı ve hataları göster
    - name: Sonuçları göster
      ansible.builtin.debug:
        msg: |
          STDOUT: {{ script_output.stdout }}
          STDERR: {{ script_output.stderr }}
      when: script_output is defined
