---
- name: AWX Playbook - Script İndirme ve Çalıştırma
  hosts: localhost
  gather_facts: no
  vars:
    input1: "{{ input1 | default('Default Input 1') }}"
    input2: "{{ input2 | default('Default Input 2') }}"

  tasks:
    - name: GitHub'dan scripti çek (curl ile)
      shell: "curl -o /tmp/awx_script.sh https://raw.githubusercontent.com/testv1c/awxscript/main/awx_script.sh"
      args:
        creates: /tmp/awx_script.sh

    - name: İndirilen scripti kontrol et
      stat:
        path: /tmp/awx_script.sh
      register: script_status

    - name: Script dosyasının durumu
      debug:
        msg: "Script mevcut mu? {{ script_status.stat.exists }}"

    - name: Dışarıdan scripti parametreler ile çalıştır
      shell: "/bin/bash /tmp/awx_script.sh '{{ input1 }}' '{{ input2 }}'"
      register: script_output
      when: script_status.stat.exists

    - name: Script çıktısını göster
      debug:
        msg: "{{ script_output.stdout }}"

    - name: Kalıcı volume içindeki dosyanın içeriğini oku
      command: cat /var/lib/awx/projects/script_output.txt
      register: file_output

    - name: Dosya içeriğini ekrana yazdır
      debug:
        msg: "{{ file_output.stdout }}"
